### ISSUE TITLE
Article: ČVUT FIT

### ISSUE THREAD

**Issue by petrhejna** [petrhejna/petrhejna#66]
* Videa z přednášek!
* Strukura je všechno, anotace videí strukturované  a odzrojované materiály (interaktivně!!!)
* Tisk diplomky, jako na PAPÍR? Wtf?
* Důležité jsou koncepty, ne definice a biflovačky technologií.
* 90% přednášené látky využije 10% studentů WTF? -> model kdy nejsou sstuddijní plány a kždý si sbírá kredity za předměty co ho baví -> zajímají, a chce se tím ve své profesní kariéře zabývat.
* Zrušit státnice WTF? jako k čemu to je?
* Valenta má dobrý přednášky (z videí).
* Vašata je borec, dělá nalejvárny na státnice

**Comment by Achse** [comment]
Zákon o vysokých školách | ČÁST ČTVRTÁ | § 46
> (3) Studium se řádně ukončuje státní závěrečnou zkouškou, jejíž součástí je obhajoba diplomové práce. V oblasti lékařství a veterinárního lékařství a hygieny se studium řádně ukončuje státní rigorózní zkouškou.
http://zakony.centrum.cz/zakon-o-vysokych-skolach/cast-4-paragraf-46
